version: '3'
services:
  mysql-db:

    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 3221
      MYSQL_DATABASE: epic_schema
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      dockerfile: dockerfile-SQL

  spring-app:
    build:
      context: .
    ports:
      - "8095:8095"
    depends_on:
      - mysql-db

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/epic_schema
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 3221



